### ISSUE TITLE
Dreambox (Enigma2) as live Input

### ISSUE THREAD

**Issue by c-o-m-m-a-n-d-e-r** [m1k1o/go-transcode#47]
Hi,
are you interessted in building a Input Config for automatic load Channels from a Dreambox (or Enigma 2 based STB) ?
Will be my first steps in go but i can try building it if you want.

Having here a Dreambox 920 with two FBC Tuner (1x Sat and 1x Cable).

Config can be look like:

```
enigma2:
  ip: x.x.x.x
  port: 8001
  bouquet: "Favorites TV"
```

and then its loading Channels for Live Streaming

**Comment by c-o-m-m-a-n-d-e-r** [comment]
added an PR
https://github.com/m1k1o/go-transcode/pull/48

**Comment by m1k1o** [comment]
Thank you for your PR, I modified it following way. Replaced `ip` and `port` with `webif-url` and `stream-url`, where `stream-url` is optional. If it is not specified, it will use hostname from `webif-url` and port `8001`.

With this approach you can have:
- Webif on different port than default `80`.
- Webif and stream protected by password (different if you like).
- They also can be behind reverse proxy

Simplest configuration (optionally with password):
```yaml
enigma2:
  webif-url: http://192.168.1.10/
  bouquet: "Skylink Slovak Republic"
```

You could have your enigma2 exposed to the internet, using HTTPs and password protected:
```yaml
enigma2:
  webif-url: https://user:pass@example.com/enigma2/
  stream-url: https://user:pass@example.com:5000
  bouquet: "Skylink Slovak Republic"
```
